apiVersion: v1
kind: Service
metadata:
  name: prod-backend
  namespace: prod-env
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-name: "prod-backend-nlb"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "${SECURITY_GROUP_ID}"
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "true"
    service.beta.kubernetes.io/load-balancer-source-ranges: "${ALLOWED_CIDR_BLOCKS}"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "5432"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=prod,Product=backend,Team=database,CostCenter=${COST_CENTER},Confidentiality=high,ManagedBy=kubernetes"
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: prod-backend
    env: prod
